# Generated by Django 5.0.6 on 2026-05-25 15:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Document title (filename by default)", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the document",
                        null=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The uploaded PDF file", upload_to="documents/"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        default=0, help_text="File size in bytes"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("extracting", "Extracting"),
                            ("extracted", "Text Extracted"),
                            ("chunking", "Chunking"),
                            ("processed", "Fully Processed"),
                            ("failed", "Processing Failed"),
                        ],
                        db_index=True,
                        default="uploaded",
                        help_text="Current processing status",
                        max_length=20,
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True,
                        help_text="Full text extracted from the PDF",
                        null=True,
                    ),
                ),
                (
                    "page_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of pages in the document"
                    ),
                ),
                (
                    "faiss_index_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the FAISS vector index for this document",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if processing failed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who uploaded this document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chunk_index",
                    models.PositiveIntegerField(
                        help_text="Sequential index of this chunk within the document"
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The text content of this chunk"),
                ),
                (
                    "page_number",
                    models.PositiveIntegerField(
                        default=0, help_text="Page number in the original document"
                    ),
                ),
                ("char_count", models.PositiveIntegerField(default=0)),
                ("word_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The document this chunk belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="documents.uploadeddocument",
                    ),
                ),
            ],
            options={
                "db_table": "document_chunks",
                "ordering": ["document", "chunk_index"],
            },
        ),
        migrations.AddIndex(
            model_name="uploadeddocument",
            index=models.Index(
                fields=["user", "status"], name="documents_user_id_10766e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadeddocument",
            index=models.Index(
                fields=["created_at"], name="documents_created_3c6eaa_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentchunk",
            unique_together={("document", "chunk_index")},
        ),
    ]
